name: HitePro MQTT Bridge
version: "1.1.2"
slug: hitepro_mqtt_bridge
description: Bridge between HitePro and Home Assistant via MQTT
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: true
ingress_port: 8099
services:
  - mqtt:want
options:
  hitepro_json_url: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  base_topic: "hitepro"
  discovery_prefix: "homeassistant"
  hitepro_device_prefix: "/devices/hite-pro/controls"
  log_level: "info"
  cover_travel_time: 190
schema:
  hitepro_json_url: str
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  base_topic: str
  discovery_prefix: str
  hitepro_device_prefix: str
  log_level: list(info|debug|warning|error)
  cover_travel_time: int
